update setup script

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,33 +1,18 @@
-#!/usr/bin/env ruby
-require "fileutils"
+#!/usr/bin/env bash
+# exit on error
+set -o errexit
 
-# path to your application root.
-APP_ROOT = File.expand_path("..", __dir__)
+echo "--- Building docker image =="
+docker-compose build #--no-cache
 
-def system!(*args)
-  system(*args, exception: true)
-end
+echo "== Install dependencies =="
+docker-compose run api bundle install
 
-FileUtils.chdir APP_ROOT do
-  # This script is a way to set up or update your development environment automatically.
-  # This script is idempotent, so that you can run it at any time and get an expectable outcome.
-  # Add necessary setup steps to this file.
+echo "== Removing old logs and tempfiles =="
+docker-compose run api bundle exec rails log:clear tmp:clear
 
-  puts "== Installing dependencies =="
-  system! "gem install bundler --conservative"
-  system("bundle check") || system!("bundle install")
+echo "== Setup database =="
+docker-compose run api bundle exec bundle exec rails db:prepare data:migrate
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?("config/database.yml")
-  #   FileUtils.cp "config/database.yml.sample", "config/database.yml"
-  # end
-
-  puts "\n== Preparing database =="
-  system! "bin/rails db:prepare"
-
-  puts "\n== Removing old logs and tempfiles =="
-  system! "bin/rails log:clear tmp:clear"
-
-  puts "\n== Restarting application server =="
-  system! "bin/rails restart"
-end
+echo "Setup done!"
+echo "run 'docker-compose up api' to start application server or 'docker-compose run api bash' to open terminal in the api service"
