add test coverange to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,6 +5,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       POSTGRES_HOST: localhost
+      MINIMUM_COVERAGE: 97
 
     services:
       database:
@@ -32,3 +33,19 @@ jobs:
 
       - name: Lint
         run: bundle exec rubocop
+
+      - name: Validate Coverage
+        run: |
+          covered_percent=$(cat coverage/coverage.json | jq -r '.metrics.covered_percent');
+          re='^[+-]?[0-9]+([.||,][0-9]+)?$';
+          if ! [[ $covered_percent =~ $re ]]; then 
+            echo "WARNING :: Couldn't get coverage from artifact.";
+            exit 0
+          fi
+          required_coverage=${{env.MINIMUM_COVERAGE}};
+          if [ $covered_percent -le $required_coverage ]; then
+            echo "Coverage ($covered_percent%) is below the required threshold of $required_coverage%.";
+            exit 1
+          else
+            echo "Coverage ($covered_percent%) passed the required threshold of $required_coverage%."
+          fi
